chore: additional error handling

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -205,7 +205,10 @@ runs:
       if: ${{ !env.ARTIFACT_URL && inputs.sign }}
       run: |
         KEYSTORE_TARGET_PATH="$ANDROID_SOURCE_DIR/$APP_NAME/${{ inputs.keystore-path }}"
-        mkdir -p "$(dirname "$KEYSTORE_TARGET_PATH")"
+        mkdir -p "$(dirname "$KEYSTORE_TARGET_PATH")" || {
+          echo "Failed to create keystore directory: $(dirname "$KEYSTORE_TARGET_PATH")"
+          exit 1
+        }
         if [ -n "${{ inputs.keystore-file }}" ]; then
           cp "${{ inputs.keystore-file }}" "$KEYSTORE_TARGET_PATH"
         else
